pragma Singleton
import QtQuick

QtObject {{
  // Generated by pywal — do not edit. Source template:
  //   ~/.config/wal/templates/colors-quickshell.qml

  readonly property color bg:      "{background}"
  readonly property color fg:      "{foreground}"
  readonly property color fgDim:   "{color8}"
  readonly property color surface: "{color0}"

  readonly property color accent:  "{color4}"
  readonly property color accent2: "{color5}"
  readonly property color warn:    "{color1}"
  readonly property color ok:      "{color2}"
  readonly property color info:    "{color6}"

  // Derived (computed at QML runtime, not by pywal)
  readonly property color border: Qt.rgba(accent.r, accent.g, accent.b, 0.30)
  readonly property color hover:  Qt.rgba(accent.r, accent.g, accent.b, 0.15)
}}
