# General
windowrule {
  name = general
  match:class = .*
  match:class = ^$
  
  allows_input = on
  suppress_event = maximize
}

# Pavucontrol floating
windowrule {
  name = pavucontrol-floating
  match:class = (.*org.pulseaudio.pavucontrol.*)

  size = 375 570
  move = (min(max((monitor_w*1)\,0)\,monitor_w-window_w)) (min(max((monitor_h*0)\,0)\,monitor_h-window_h))
  pin = on

}
# Discord floating
windowrule {
  name = discord-floating
  match:initial_title = (.*Discord.*)

  float = on
  size = 1600 1000
  center = on
}

# PulseUI
windowrule {
  name = pulseUI-rules
  match:class = (pulseUI)

  size = 300 600
  center = on
  allows_input = on
}

# Dolphin File Explorer floating
windowrule {
  name = dolphin-floating
  match:class = (org.kde.dolphin)
  
  float = on
  size = 955 590
}

# Bitwarden floating
windowrule {
  name = bitwarden-floating
  match:title = (Bitwarden)
  
  float = on
}

